// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// Flutter - Should firebase_options.dart be added to gitignore?
/// https://stackoverflow.com/questions/71432691/flutter-should-firebase-options-dart-be-added-to-gitignore
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZbcN77Vc9Yfzgl0l0ITJczJwXlC0Ce0',
    appId: '1:233742745865:android:5b6970051bbd8e3f7013d8',
    messagingSenderId: '233742745865',
    projectId: 'chatgpt-compose-ryu',
    storageBucket: 'chatgpt-compose-ryu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq1FaunWd7Zqj3IQO_86Fpu7q4HR45_fU',
    appId: '1:233742745865:ios:9912135fe326afd27013d8',
    messagingSenderId: '233742745865',
    projectId: 'chatgpt-compose-ryu',
    storageBucket: 'chatgpt-compose-ryu.appspot.com',
    iosBundleId: 'com.example.ryChat',
  );
}
