name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run Melos bootstrap
        run: melos bootstrap

      - name: Run tests
        run: melos run test

      - name: Run lint
        run: melos run lint

      - name: Analyze
        run: melos run analyze

      - name: Build
        run: melos run build_runner