name: test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Mark Flutter directory as safe
        run: git config --global --add safe.directory '*'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
          cache: true
          cache-key: "flutter-${{ runner.os }}-stable-${{ hashFiles('pubspec.yaml') }}"
          cache-path: "${{ runner.tool_cache }}/flutter/stable-${{ hashFiles('pubspec.yaml') }}"
          pub-cache-key: "flutter-pub-${{ runner.os }}-stable-${{ hashFiles('pubspec.yaml') }}"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/stable-${{ hashFiles('pubspec.yaml') }}"

      - name: Verify Flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run Melos bootstrap
        run: flutter pub global activate melos && melos bootstrap

      - name: Run tests
        run: melos run test
